### ISSUE TITLE
Đặc tả usercase 

### ISSUE THREAD

**Issue by LeHaiDangSPKT** [LeHaiDangSPKT/talkdesk_g5#10]
- [x] 1. Đặc tả chức năng đăng nhập.
- [x] 2. Đặc tả chức năng đăng ký.
- [x] 3. Đặc tả chức năng quên mật khẩu/ đổi mật khẩu.
- [x] 4. Đặc tả chức năng quản lí thông tin tài khoản.
- [x] 5. Đặc tả chức năng đăng xuất.
- [x] 6. Đặc tả chức năng tìm kiếm.
- [x] 7. Đặc tả chức năng liên hệ hỗ trợ khách hàng.

**Comment by LakLN** [comment]
Task 1:
https://docs.google.com/document/d/1OkeJ2m8E0gsHEmtx5vSfIv1DNhI0QsB1PxGgmHzuRkM/edit?usp=sharing

**Comment by LakLN** [comment]
Task 3:
https://docs.google.com/document/d/1g35r22M9XmuBI90G7tyBjpoY7KB7BObxesgKMWZRsPk/edit?usp=sharing

**Comment by LakLN** [comment]
Task 4:
https://docs.google.com/document/d/16U3AsXhuqhgvaCL0dfdERyNQPEXk84BPxWaVy9TFstg/edit?usp=sharing

**Comment by LakLN** [comment]
Task 5:
https://docs.google.com/document/d/1u8korKfOEpj23XfsyblrN99jnCZ7a296mXq1zvFu0Dg/edit?usp=sharing

**Comment by LakLN** [comment]
Task 6:
https://docs.google.com/document/d/1w8FgYrzDu3gBu7eBcfk8nhoc3uU8m9Rh9mBO3IG0IEQ/edit?usp=sharing

**Comment by LakLN** [comment]
Task 7:
https://docs.google.com/document/d/1pcje8HdrZuBDFLLYWBx3o3l7CQTFlIYg2jJyoufHjjw/edit?usp=sharing
