### ISSUE TITLE
Use case diagram

### ISSUE THREAD

**Issue by LeHaiDangSPKT** [LeHaiDangSPKT/talkdesk_g5#11]
- [x] 1.  Xác định actor
- [x]  2. Xác định các use case
- [x] 3. Mối liên hệ giữa actor và acctor
- [x]  4. Mối liên hệ giữa actor và use case
- [x]  5. Mối liên hệ giữa use case và use case 
- [x]  6. Vẽ use case diagram
- [x] 7. Một số lưu ý khi vẽ use case diagram

**Comment by thanhvanba** [comment]
Hoàn thành Task1
https://docs.google.com/document/d/15zogkv6M2Yc-bGOKjtz8gC8n2-G1s86ZYiI_BzBmc80/edit

**Comment by thanhvanba** [comment]
Hoàn thành Task
https://docs.google.com/document/d/1PWbO5t4ZnjItb0D94FLAlMCk48KzAKual6bCarKXNvI/edit?usp=drivesdk

**Comment by thanhvanba** [comment]
Hoàn thành Task4
https://docs.google.com/document/d/115zdkPFL97FzkI-TqgmOK2HZPT7lzLl1yK7jBhbo-FQ/edit

**Comment by thanhvanba** [comment]
Hoàn thành Task5
https://docs.google.com/document/d/190_Ks2DGHIju0FNZmi9xTBI_vE3_NbIdDv72E2iXRnc/edit

**Comment by thanhvanba** [comment]
Hoàn thành Task6
https://docs.google.com/document/d/1KCv8qVIh8BGWIfR3b_TsM-2QpKXwCF6qaf0aL1M0oRM/edit

**Comment by thanhvanba** [comment]
Hoàn thành Task7
https://docs.google.com/document/d/13EmRDVDJlV3Mm5rqNJ85vQ_sMiJyY28gS2ZZ-nQEqHo/edit
