### ISSUE TITLE
 Software Requirement Specification

### ISSUE THREAD

**Issue by thanhvanba** [LeHaiDangSPKT/talkdesk_g5#17]
- [x] 1. Introduction 
- [x] 2. Overall Description
- [x] 3. System Features
- [x] 4. External Interface Requirements
- [x] 5. Other Nonfunctional Requirements

**Comment by thanhvanba** [comment]
Hoàn thành Task 1
https://docs.google.com/document/d/1aLEBkAKMudnE6dYpfjJ6-kSFXdH38zn4/edit#

**Comment by thanhvanba** [comment]
Hoàn thành Task2
https://docs.google.com/document/d/1aLEBkAKMudnE6dYpfjJ6-kSFXdH38zn4/edit#

**Comment by thanhvanba** [comment]
Hoành thành Task5
https://docs.google.com/document/d/1aLEBkAKMudnE6dYpfjJ6-kSFXdH38zn4/edit#

**Comment by LakLN** [comment]
Hoàn thành Task 3:
https://docs.google.com/document/d/1aLEBkAKMudnE6dYpfjJ6-kSFXdH38zn4/edit#

**Comment by LakLN** [comment]
Hoàn thành Task 4:
https://docs.google.com/document/d/1aLEBkAKMudnE6dYpfjJ6-kSFXdH38zn4/edit#
