### ISSUE TITLE
Chuẩn bị font chữ và màu chủ đạo của trang web để làm biến trong css

### ISSUE THREAD

**Issue by LeHaiDangSPKT** [LeHaiDangSPKT/talkdesk_g5#4]
- [x]  3. Xác định các font chữ của website
- [x]  4. Xác định màu chữ trong Website
- [x]  5. Xác định cỡ chữ dùng trong website
- [x]  6. Xác định màu chủ đạo của website
- [x]  7. Kiểm tra kích thước từng thành phần trên website

**Comment by thanhvanba** [comment]
Hoàn thành Task3, Task4, Task5
[Task3-5.docx](https://github.com/LeHaiDangSPKT/talkdesk_g5/files/11012063/Task3-5.docx)

**Comment by thanhvanba** [comment]
Hoàn thành Task7
[Task7.docx](https://github.com/LeHaiDangSPKT/talkdesk_g5/files/11016220/Task7.docx)
